version: "3.8"

services:
  sr6-twitter-bot:
    build: .
    container_name: sr6-twitter-bot

    restart: unless-stopped
    cap_add:
      - sys_nice
    stop_grace_period: 30s

    volumes:
      - ./data:/usr/src/app
